name: API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Dockerized API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Docker Image
        run: docker build -t bookstore-tests .

      - name: Execute Tests in Docker
        run: |
          
          docker run --name test-container bookstore-tests

      - name: Extract Allure Results
        if: always()
        run: |
          
          docker cp test-container:/app/target/allure-results ./allure-results

      - name: Upload Test Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-artifact
          path: allure-results
          retention-days: 5